apiVersion: v1
kind: Service
metadata:
  name: btc-exporter
  namespace: finance
spec:
  selector:
    app: btc-exporter
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP

